[build]
  functions = "./netlify/functions"

[dev]
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "https://munchhunt.netlify.app/*"
to = "https://munchhunt.xyz/:splat"
status = 301
force = true
